### ISSUE TITLE
Please add list of supported/tested browsers

### ISSUE THREAD

**Issue by eugef** [hunzaboy/CSS-Checkbox-Library#4]

**Comment by joshuawalcher** [comment]
Tested in Chrome 49+, Firefox 52+, IE11+ and all working well.

Tested in IE9. Most work without animations. About a third in the latter half do not work.

**Comment by hunzaboy** [comment]
Thanks for Testing. 

Fixed issues with IE9 and Safari on Windows. Waiting for someone to test on MacOS.

P.S I am a windows guy :)

**Comment by eugef** [comment]
What about mobile browsers?

**Comment by hunzaboy** [comment]
Fixed the demo site on mobile devices. Will be testing on different devices. All of them are working fine except the 15th. 

If you can help me with the testing, then it will be great.

**Comment by joshuawalcher** [comment]
Demo is confirmed working in IE9 now.

**Comment by hunzaboy** [comment]
Tested in Chrome for Android and other devices. I am closing this issue now. Fell free to open it when faced bugs.
